### ISSUE TITLE
Rantly makes Rubocop sad

### ISSUE THREAD

**Issue by Ana06** [rantly-rb/rantly#28]
Using Rubocop default configuration, which I understand is the default one and the one more people use, when using the syntax documented in Rantly for rspec there are offenses in two cops: `Style/BlockDelimiters` and `Style/MultilineBlockChain`.

So, when using Rubocop together with Rantly for writing rspec tests, there are two options. Using the Rubocop suggested syntax. I don't like this option because someone else working on the project may read the code and in case of doubt he will come to Rantly documentation and using different syntax make it more difficult to understand. The second option is to disable the cops for the Rantly code or for the whole spec folder, which is also not nice.

I would suggest **changing the documentation in Rantly to use Rubocop defaults**. :wink:

**Comment by bbugh** [comment]
It's RSpec common style to do something like this: 

```ruby
expect {
  # blah blah
}.to change

expect {
  # blah blah
}.to raise_error
```

which doesn't have anything to do with this gem. If you want to make Rubocop be smarter about the block delimiters, change the enforced style to `semantic` instead of the (poor imo) defaults:

```yaml
Style/BlockDelimiters:
  EnforcedStyle: semantic
```

*Additional context:* https://github.com/bbatsov/rubocop/pull/1731

This is just one of the many defaults that Rubocop uses that aren't very good for the Ruby community at large.

**Comment by Ana06** [comment]
@bbugh 

RSpec does:

``` Ruby
expect {'# blah blah'}.to change
expect {'# blah blah'}.to raise_error
```

so, inline style, which follow Rubocop rules.

However, I was not speaking about the `expect` part, but about:

``` Ruby
property_of {
  len = integer
  [len,array(len){integer}]
}
```

but it is true that it is normal to exclude `MultilineBlockChain` for rspec anyway. Ok, I'll close this.
